### ISSUE TITLE
Can you give me npm `tson` package? 

### ISSUE THREAD

**Issue by samchon** [kba/turtleson#1]
I am developer of [typescript-json](https://github.com/samchon/typescript-json) and wanna shorter package name.

If you don't plan to maintain the `tson` package, can you give me it?

@kba

**Comment by kba** [comment]
I could but am not keen on republishing it in another namespace and possibly break deployments.

Also, I really do not appreciate you asking about this publicly in the chat of my day job.

**Comment by samchon** [comment]
Thanks for replying and sorry for talking on your working gitter channel. 

I should find another package name.
